name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v2

      # Step 2: Set up Node.js environment with the latest LTS version
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'  # Use the latest LTS version of Node.js

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # Step 5: Build Application and Run unit tests
      - name: Build and Test
        env:
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
      # Step 1: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 2: Create CodeDeploy Deployment
      - name: Deploy to EC2 with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name agrowtein-codedeploy \
            --deployment-group-name agrowtein-deployment-group \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --region ap-south-1 
